from rich.console import Console
from rich.table import Table
from jinja2 import Template

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Metron GitHub Risk Report - {{ target }}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
<style>
 body{font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:2rem;color:#111}
 h1{font-size:1.6rem;margin-bottom:0.5rem}
 .sub{color:#666;margin-bottom:1.5rem}
 table{width:100%;border-collapse:collapse;margin-top:1rem}
 th,td{border:1px solid #eee;padding:.6rem;text-align:left}
 th{background:#fafafa}
 .sev-High{color:#b91c1c;font-weight:600}
 .sev-Medium{color:#a16207;font-weight:600}
 .sev-Low{color:#065f46;font-weight:600}
 .sev-None{color:#374151}
 .pill{display:inline-block;background:#f3f4f6;border:1px solid #e5e7eb;border-radius:999px;padding:.2rem .6rem;margin-right:.3rem}
 details{margin:.6rem 0}
 code{background:#f6f8fa;padding:.1rem .3rem;border-radius:.25rem}
</style>
<h1>GitHub Risk Report — {{ target }} ({{ mode }})</h1>
<div class="sub">Generated by Metron Scanner</div>
<table>
<thead><tr><th>Repository</th><th>Issues</th><th>Severity</th></tr></thead>
<tbody>
{% for repo in repos %}
<tr>
  <td><a href="{{ repo.html_url }}" target="_blank">{{ repo.name }}</a></td>
  <td>{% if repo.issues %}{% for i in repo.issues %}<span class="pill">{{ i }}</span>{% endfor %}{% else %}—{% endif %}
    {% if repo.details %}
      <details><summary>Details</summary>
        {% for k,items in repo.details.items() if items %}
        <div><strong>{{ k }}</strong>
          <ul>
          {% for it in items %}
            <li><code>{{ it.path }}</code>{% if it.get('type') %} — {{ it.type }}{% endif %}{% if it.get('snippet') %} — <code>{{ it.snippet }}</code>{% endif %}</li>
          {% endfor %}
          </ul>
        </div>
        {% endfor %}
      </details>
    {% endif %}
  </td>
  <td class="sev-{{ repo.severity }}">{{ repo.severity }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</html>
"""

def print_table(results):
    c = Console()
    t = Table(title=f"GitHub Risk Report — {results['target']} ({results['mode']})")
    t.add_column("Repository", style="bold")
    t.add_column("Issues")
    t.add_column("Severity", style="bold")
    for r in results["repos"]:
        issues = ", ".join(r["issues"]) if r["issues"] else "—"
        t.add_row(r["name"], issues, r["severity"])
    c.print(t)

def write_html_report(results, path):
    tmpl = Template(HTML_TEMPLATE)
    html = tmpl.render(**results)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
from rich.console import Console
from rich.table import Table
from jinja2 import Template

HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>Metron GitHub Risk Report - {{ target }}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet">
<style>
 body{font-family:Inter,system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:2rem;color:#111}
 h1{font-size:1.6rem;margin-bottom:0.5rem}
 .sub{color:#666;margin-bottom:1.5rem}
 table{width:100%;border-collapse:collapse;margin-top:1rem}
 th,td{border:1px solid #eee;padding:.6rem;text-align:left}
 th{background:#fafafa}
 .sev-High{color:#b91c1c;font-weight:600}
 .sev-Medium{color:#a16207;font-weight:600}
 .sev-Low{color:#065f46;font-weight:600}
 .sev-None{color:#374151}
 .pill{display:inline-block;background:#f3f4f6;border:1px solid #e5e7eb;border-radius:999px;padding:.2rem .6rem;margin-right:.3rem}
 details{margin:.6rem 0}
 code{background:#f6f8fa;padding:.1rem .3rem;border-radius:.25rem}
</style>
<h1>GitHub Risk Report — {{ target }} ({{ mode }})</h1>
<div class="sub">Generated by Metron Scanner</div>
<table>
<thead><tr><th>Repository</th><th>Issues</th><th>Severity</th></tr></thead>
<tbody>
{% for repo in repos %}
<tr>
  <td><a href="{{ repo.html_url }}" target="_blank">{{ repo.name }}</a></td>
  <td>{% if repo.issues %}{% for i in repo.issues %}<span class="pill">{{ i }}</span>{% endfor %}{% else %}—{% endif %}
    {% if repo.details %}
      <details><summary>Details</summary>
        {% for k,items in repo.details.items() if items %}
        <div><strong>{{ k }}</strong>
          <ul>
          {% for it in items %}
            <li><code>{{ it.path }}</code>{% if it.get('type') %} — {{ it.type }}{% endif %}{% if it.get('snippet') %} — <code>{{ it.snippet }}</code>{% endif %}</li>
          {% endfor %}
          </ul>
        </div>
        {% endfor %}
      </details>
    {% endif %}
  </td>
  <td class="sev-{{ repo.severity }}">{{ repo.severity }}</td>
</tr>
{% endfor %}
</tbody>
</table>
</html>
"""

def print_table(results):
    c = Console()
    t = Table(title=f"GitHub Risk Report — {results['target']} ({results['mode']})")
    t.add_column("Repository", style="bold")
    t.add_column("Issues")
    t.add_column("Severity", style="bold")
    for r in results["repos"]:
        issues = ", ".join(r["issues"]) if r["issues"] else "—"
        t.add_row(r["name"], issues, r["severity"])
    c.print(t)

def write_html_report(results, path):
    tmpl = Template(HTML_TEMPLATE)
    html = tmpl.render(**results)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html)
